package:
  name: qmdesc
  version: 1.0

source:
  git_rev: v1.0
  git_url: https://github.com/yanfeiguan

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    -

about:
  home:
